name: saas_analytics
version: 1.0.0
config-version: 2

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]
clean-targets:
  - target
  - dbt_packages

models:
  startup_saas_analytics:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: marts
      +materialized: table