select
    account_id,
    company_name,
    signup_date as signup_at,
    to_date(signup_date) as signup_date,
    date_trunc('month', signup_date)::date as signup_month,
    trial_started_at,
    trial_ended_at,
    converted_to_paid_at,
    activated_at,
    activation_score,
    lower(segment) as segment,
    lower(acquisition_channel) as acquisition_channel,
    region,
    lower(industry) as industry,
    lower(billing_period) as billing_period,
    lower(initial_plan) as initial_plan,
    initial_paid_seats,
    seat_capacity,
    user_capacity,
    user_id_start,
    user_id_end,
    iff(activated_at is not null, true, false) as is_activated,
    iff(converted_to_paid_at is not null, true, false) as is_paid_converted,
    iff(converted_to_paid_at is not null and billing_period = 'annual', true, false) as started_annual,
    datediff('day', signup_date, activated_at) as days_signup_to_activation,
    datediff('day', trial_started_at, converted_to_paid_at) as days_trial_to_paid
from {{ source('raw', 'accounts') }}